" vim:fdm=marker:fdl=0
" Plugins {{{
call plug#begin('~/.vim/plugged')
Plug 'vimwiki/vimwiki'
Plug 'ycm-core/YouCompleteMe'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()
" }}}
" {{{ General settings
set nocompatible
filetype plugin on
syntax on

" time to wait before trigger plugins default:4000
" used by vim-gitgutter
set updatetime=200

set spelllang=en_us,de_ch

" Better command-line completion
set wildmenu

" Case insensitive search
set ignorecase
set smartcase
" Highlight search
set hlsearch
" }}}
" Styling {{{
set background=dark
:color desert
:set number relativenumber
" }}}
" Shortcuts {{{
set pastetoggle=<F2>
map <F4> :YcmCompleter GoToDefinitionElseDeclaration<CR>
" }}}
" Folding {{{
set foldlevelstart=2
nnoremap <space> za
" }}}
" Vimwiki {{{
let g:vimwiki_list = [{
\ 'path': '~/vimwiki/',
\ 'syntax': 'markdown',
\ 'ext': '.md'}]
let g:vimwiki_folding = 'expr'
 " Diary {{{
command! Diary VimwikiDiaryIndex
augroup vimwikigroup
  autocmd!
  " automatically update links on read diary
  autocmd BufRead,BufNewFile diary.md VimwikiDiaryGenerateLinks
augroup end
 " }}}
" }}}
" Easy Motion {{{
let g:EasyMotion_do_mapping = 0 " Disable default mappings

map s <Plug>(easymotion-bd-f)
nmap s <Plug>(easymotion-overwin-f)

map w <Plug>(easymotion-bd-w)
nmap w <Plug>(easymotion-overwin-w)

" Turn on case-insensitive feature
let g:EasyMotion_smartcase = 1

let g:EasyMotion_skipfoldedline = 0
 " }}}
" Git {{{
let g:gitgutter_set_sign_backgrounds = 1
highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1

" move between hunks: '[c' ']c'
" preview, stage, undo <leader>hp, hs, hu
" }}}
" Find Files {{{
map ; :GFiles<CR>
" }}}
